language: php
php:
 - 7.1
 - 7.2

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpstan analyse -l 7  -c phpstan.neon src/Commands src/Config src/DI src/Diagnostics src/Exception src/Factory src/Model src/Settings src/ClientProvider.php src/Settings.php
