language: php
php:
 - 7.1
 - 7.2

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpstan analyse -l 7 -c phpstan.neon src tests
  - vendor/bin/phpcs --standard=vendor/spameri/coding-standard/src/ruleset.xml src tests
